export const AMAP_API_KEY: string = 'YOUR_AMAP_HARMONY_KEY';
export const AMAP_WEB_SERVICE_API_KEY: string = 'YOUR_AMAP_WEB_SERVICE_KEY';
export const AMAP_COORDINATE_CONVERT_URL: string = 'https://restapi.amap.com/v3/assistant/coordinate/convert';

export const DEEPSEEK_API_KEY: string = 'YOUR_DEEPSEEK_API_KEY';
export const DEEPSEEK_CHAT_COMPLETIONS_URL: string = 'https://api.deepseek.com/chat/completions';
export const DEEPSEEK_MODEL: string = 'deepseek-v4-flash';
